lune-climate/lune-shipping-csv-tool

README.md
We've refreshed our api reference which has different links.
=> README.md: update documentation links

package.json
I want to release [1].
[1] 92ac4d2d0e1e ("Support geographic coordinates in the input CSV (#3)")
=> Bump the package version to 1.0.5

.github/README.md
Doing so to keep instructions somehow consistent.
=> Copy leg_coordinates instructions to .github/README.md

package.json, src/index.ts, yarn.lock
If there are a lot of input rows the application may take a while to finish and it's not clear if something's wrong or if everything's ok.
Let's display a progress bar updated on each processed rows so there's some indication of what's going on.
=> Display a progress bar

package.json
This is what "yarn install <anything>" or some other package.json-modifying yarn command will produce and it's annoying to keep discarding that change, let's just commit it.
=> Reformat package.json

src/index.ts, src/utils.ts
This is basically applying our eslint and prettier rules to the code.
=> Fix the linting rules violations

README.md
The grouping section was kind of redundant.
=> Reduce the installation instructions nesting

package.json
We'll be using both eslint and prettier for linting and we have configuration for both so it's only reasonable to also use both of them to make the code follow the expected rules.
=> Have one script for fixing both eslint and prettier issues

README.md
There was a significant overlap between and it was confusing where one of them appeared much earlier in the file while the other one was at the end.
=> Merge two very similar readme sections

README.md
Just to make it easier to navigate and to see where one can go from the section they are right now.
=> Add some cross-sections references to the readme

src/index.ts, src/utils.ts
For consistency with the rest of the functions in this project and internal Lune code.
=> Convert function constants to function statements

src/index.ts, src/types.ts, src/utils.ts
We've been a little messy in this regard, I intend to add some linting rules soon that will enforce this.
=> Sort imports

src/index.ts, src/utils.ts
These values are never null-ish.
=> Remove two unnecessary conditions

.eslintrc.cjs, package.json, src/index.ts, yarn.lock
This is mostly what we use for the Lune backend code with some minor changes to fit this project.
Should let us avoid some common mistakes in the future.
=> Expand the linting rules

.github/dependabot.yml
To help up keep them up to date.
=> Configure dependency updates through Dependabot

README.md
Good to see at a glance how good (or bad!) our coverage is.
=> Present the Codecov test coverage badge in the readme

jest.config.cjs, src/test.ts, src/utils.ts
A humble initial test suite to give us more confidence in the codebase.
=> Unit test parseCoordinates()

.github/dependabot.yml
=> Move dependabot updates schedule to weekly

package.json, yarn.lock
This version contains more defensive error handling which makes it less likely it hides unexpected exceptions[1].
[1] https://github.com/lune-climate/lune-ts/pull/256
=> Update the Lune TS client to 2.11.0

package.json, yarn.lock
This contains an updated Lune TS client version[1] that's less likely to treat unexpected exceptions as Axios connection errors (and, in consequence, less likely to hide issues).
[1] https://github.com/lune-climate/lune-shipping-csv-tool/pull/246
=> Release version 3.0.2

package.json
Version 3.0.2 has been published incorrectly and therefore removed.
=> Upgrade to 3.0.3

package.json, yarn.lock
This version fixes connection error handling and reporting[1][2].
[1] https://github.com/lune-climate/lune-shipping-csv-tool/pull/250
[2] https://github.com/lune-climate/lune-ts/pull/261
=> Release version 3.0.4

README.md
Add deprecation notice to README.md.
=> Communicate deprecation
