lune-climate/lune-shipping-csv-tool

src/index.ts

The client library already converts all exceptions to error values internally so any error handling we need to do is just about handling the values returned by the client.
Note that there's some code here that isn't strictly speaking correct (mainly the value we give the description constant, this also forces us to have that type assertion that shouldn't be necessary) but that's something that was already present here and to be improved in a separate PR.

Eliminate exceptions from the API call flow

---

src/index.ts

Making an unbounded number of concurrent API calls was not necessary for small number of inputs (little to no gain) and actively detrimental in case of larger ones (the Lune API enforces rate limits and the code would easily hit them[1]).
[1] It's still totally possible and likely to reach the rate limits,
code to handle that to come in a separate PR (retries).

Make API calls sequentially, not all at once

---

src/index.ts
src/utils.ts

Previously we would bail on the very first attempt to create an estimate for a given journey which didn't make for a great user experience (particularly in case of hitting the API rate limit which is bound to happen every now and then if we have a lot of inputs).

Retry in case of (presumably) recoverable errors

---

package.json

These aren't necessary to install and use the package, they're only used and needed during development (or running the code straight from the repository).

Move some dependencies to dev dependencies

---

package.json
yarn.lock

Just keeping this up to date. Since the client library now correctly depends on camelcase-keys and snakecase-keys (there was an issue in older versions of the library) we can ourselves stop depending on these libraries directly.

Update the Lune client to 2.2.4 (the latest version)

---

.env
README.md
package.json
src/index.ts
yarn.lock

It doesn't provide us any benefits in development (modifying .env forces us to keep ignoring the changes in the working directory) or in npm-/yarn-installed version (*where* would the end-user find the .env file to modify?).
It's both enough and easier for the user to provide the environment variable directly (as the readme already documents), fewer moving pieces.

Stop using dotenv

---

package.json

This is to allow us to publish a new version to NPM. I went for the minor number change because we have some new features.

Bump the version to 1.1.0

---

package.json

Turns out tsc has this --build switch[1] that only type checks and build the code when any of the input files changed. This brings the time to run "yarn build" with no changes present down to ~0.3 s in my Docker environment (compared to ~5 s previously). Full rebuilds still take ~5 seconds, naturally.
A build/ cleanup has been added on dependency installation because tsc --build doesn't handle node_modules changes well.
I went with preinstall instead of postinstall so that on every *attempt* to install dependencies we remove the files – this way even if someone interrupts the package installation we always remove the files first so we're not left in a state where we have the old build directory but some dependencies already changed (no race conditions).
[1] …

Only recompile when there are changes

---

nodemon.json
package.json
yarn.lock

It didn't offer us much value beyond what just building the project and running the compiled version provided. There was no performance benefit of using it, it essentially rebuilt everything every time it ran.

Get rid of ts-node

---

README.md

The backslashes were not necessary and since these are lists let's actually make them (Markdown) lists.

Format the input file field lists nicely

---

package.json

We're already incompatible (the start and test package.json scripts for example) and it's annoying to have Windows-specific workarounds in place, especially when we all run Unix-like systems.
The version of the package published to NPM remains Windows-compatible and end users fetching it from there aren't affected.

Stop pretending we support Windows for development

---

package.json

I figured if we have prettier in the dependencies and we have a configuration for it might as well enforce prettier formatting through the lint script.

Include prettier in the lint task

---

README.md
src/index.ts

API_KEY is a little bit too generic, let's give it a prefix so it's clear what is it and to avoid clashes with other software and other API keys.

Rename API_KEY to LUNE_API_KEY

---

package.json

We have the eslint-plugin-prettier enabled so all prettier issues are already detected by eslint (and fixed with --fix when possible).

Stop calling prettier explicitly

---

tsconfig.json

This is a TS project and we have no need for this right now. Type check everything and don't provide escape hatches.

Stop allowing importing pure JS code

---

src/types.ts
src/utils.ts

Those were internal modules we were importing from (exported from the package unintentionally).
See [1] for more information.
[1] https://github.com/lune-climate/lune-ts/pull/190

Fix Lune client library imports

---

src/index.ts
src/utils.ts

It's easier to know what's going on if the function doesn't refer to global variables to accepts the file path as a parameter.

Remove application argument parsing from writeResultsToCSV()

---

src/index.ts
src/utils.ts
tsconfig.json

It's kind of unexpected that a function called writeResultsToCSV() reads files and parses CSV so let's remove that. The long-term goal is to make this code more unit-testable too.

Remove CSV file reading from writeResultsToCSV()

---

.github/workflows/ci.yml
package.json

It lets us see right away what's tested and what's not (right now: everything's the latter), Codecov has nice code browser with coverage visible right there.
The --collectCoverageFrom parameter allows us to include all source files in the report so that ones that are never used are reported as not covered.

Report test coverage to Codecov

---

jest.config.cjs

.js extensions are required in ESM code (which ours is) but we need to tell jest how to actually find the modules to import (it doesn't understand ESM by out of the box).
$ /lune/lune-shipping-csv-tool/node_modules/.bin/jest src/ --coverage '--collectCoverageFrom=./src/**'
FAIL  src/test.ts
● Test suite failed to run
Cannot find module './utils.js' from 'src/test.ts'
3 | // TODO: Remove when this is no longer needed
4 | test('Dummy test', () => {
> 5 |     // Boo
|                  ^
6 |     parseCoordinates('asd')
7 | })
8 |
at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
at Object.<anonymous> (src/test.ts:5:18)
when we added *any* imports to test.ts.
This isn't breaking anything at the moment but is needed in order for us to have any meaningful …

Support ESM imports in tests

---

src/index.ts
src/utils.ts

Easier to see what the code does at a glance (some functions return something useful, some don't), easier to work with the code and review.

Provide explicit return types everywhere

---

package.json

Incrementing the major number to make it clear we're breaking compatibility here (and we are, in at least one case: the program expects an environment variable named LUNE_API_KEY now, used to be API_KEY).

Bump the version to 2.0.0

---

README.md
package.json

The project is called `lune-shipping-csv-tool`, call the executable
`lune-shipping-csv-tool`.
This is standard `npm` practice.
Also, some links to Github were wrong.

Rename lune-csv-calculator to lune-shipping-csv-tool

---

src/index.ts

This increases the possibility for clients to understand what they are doing wrong.
Previously, passing an incorrectly formatted `amount` would show
`The request is invalid. Parameters may be missing or are invalid`
which is not enough for debugging inputs swiftly.
Now you get:
```
"The request is invalid. Parameters may be missing or are invalid; validation_error: Provided data does not match the defined schema.: .body.shipment.mass.amount should match pattern ""^[0-9]+(\.[0-9]+)?$"", .body.shipment.containers should have required property 'containers', .body.shipment.mass.amount should match pattern ""^[0-9]+(\.[0-9]+)?$"", .body.shipment should match exactly one schema in oneOf"
```

Expand API errors if present

---

README.md

Customers who get the `EACCES: permission denied` when running `npm` don't know how to proceed.
Explain a possible solution.

Give npm EACCES error solution

---

src/utils.ts

The code has been making assumptions that the API returns distances in kilometers and CO2 amounts in tonnes.
While the API does do that (currently) it'd be great for the code to actually varify this assumption so we at least know in case it doesn't happen to be true.

Protect against unexpected units returned by the API

---

src/index.ts

This should provide an early detection of API key problems or network connectivity issues before we even get to the emission estimating stage.
This should make it more obvious when something's wrong and what to do to fix it.

Test Lune API connectivity at startup
